# Generated by Django 5.2.9 on 2025-12-05 00:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rr_id', models.CharField(max_length=255, unique=True, verbose_name='ID заявки из РР')),
                ('last_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Фамилия')),
                ('first_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя')),
                ('middle_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Отчество')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Начало периода обучения')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Окончание периода обучения')),
                ('program_name', models.TextField(blank=True, null=True, verbose_name='Программа обучения')),
                ('region', models.CharField(blank=True, max_length=255, null=True, verbose_name='Регион')),
                ('category', models.TextField(blank=True, null=True, verbose_name='Категория гражданина')),
                ('snils', models.CharField(blank=True, max_length=50, null=True, verbose_name='СНИЛС')),
                ('request_date', models.DateField(blank=True, null=True, verbose_name='Дата подачи заявки на РР')),
                ('program_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='ID программы в заявке')),
                ('current_atlas_status', models.CharField(blank=True, max_length=255, null=True, verbose_name='Текущий статус Атлас')),
                ('current_rr_status', models.CharField(blank=True, max_length=255, null=True, verbose_name='Текущий статус РР')),
                ('prev_atlas_status', models.CharField(blank=True, max_length=255, null=True, verbose_name='Предыдущий статус Атлас')),
                ('prev_rr_status', models.CharField(blank=True, max_length=255, null=True, verbose_name='Предыдущий статус РР')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
            },
        ),
        migrations.CreateModel(
            name='StatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atlas_status', models.CharField(blank=True, max_length=255, null=True, verbose_name='Статус Атлас')),
                ('rr_status', models.CharField(blank=True, max_length=255, null=True, verbose_name='Статус РР')),
                ('snapshot_dt', models.DateTimeField(verbose_name='Дата/время среза')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='history.application', verbose_name='Заявка')),
            ],
            options={
                'verbose_name': 'История статуса',
                'verbose_name_plural': 'История статусов',
                'ordering': ['-snapshot_dt'],
            },
        ),
    ]
