# Generated by Django 5.2.9 on 2025-12-05 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255, verbose_name='Имя файла')),
                ('snapshot_dt', models.DateTimeField(verbose_name='Дата/время среза (из формы)')),
                ('upload_dt', models.DateTimeField(auto_now_add=True, verbose_name='Время загрузки')),
                ('created_count', models.IntegerField(default=0, verbose_name='Создано заявок')),
                ('updated_count', models.IntegerField(default=0, verbose_name='Обновлено заявок')),
            ],
            options={
                'verbose_name': 'История импорта',
                'verbose_name_plural': 'История импортов',
                'ordering': ['-upload_dt'],
            },
        ),
    ]
