# Generated by Django 5.2.9 on 2025-12-09 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0002_importhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('enabled', models.BooleanField(default=True, verbose_name='Включено')),
                ('config_path', models.CharField(default='scraper_config.yaml', max_length=500, verbose_name='Путь к scraper_config.yaml')),
                ('interval_minutes', models.PositiveIntegerField(default=30, verbose_name='Период (минуты)')),
                ('start_time', models.TimeField(verbose_name='Начало интервала (время дня)')),
                ('end_time', models.TimeField(verbose_name='Окончание интервала (время дня)')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания действия')),
                ('last_run_at', models.DateTimeField(blank=True, null=True, verbose_name='Последний запуск')),
            ],
            options={
                'verbose_name': 'Расписание автоимпорта',
                'verbose_name_plural': 'Расписания автоимпорта',
            },
        ),
    ]
