# Generated by Django 5.2.9 on 2026-01-28 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0003_exportschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='LMS',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Программа в LMS'),
        ),
        migrations.AddField(
            model_name='application',
            name='atlas_status',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Статус заявки в Атлас'),
        ),
        migrations.AddField(
            model_name='application',
            name='birthday',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AddField(
            model_name='application',
            name='contact',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Контактная информация'),
        ),
        migrations.AddField(
            model_name='application',
            name='contry',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Гражданство'),
        ),
        migrations.AddField(
            model_name='application',
            name='employment',
            field=models.BooleanField(default=False, verbose_name='Трудоустройство'),
        ),
        migrations.AddField(
            model_name='application',
            name='passport',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Серия и номер паспорта'),
        ),
        migrations.AddField(
            model_name='application',
            name='passport_issued_at',
            field=models.DateField(blank=True, null=True, verbose_name='Дата выдачи'),
        ),
        migrations.AddField(
            model_name='application',
            name='passport_issued_by',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Кем выдан паспорт'),
        ),
        migrations.AddField(
            model_name='application',
            name='reg_address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Место регистрации'),
        ),
        migrations.AddField(
            model_name='application',
            name='rr_application',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Номер заявления на РР'),
        ),
        migrations.AddField(
            model_name='application',
            name='rr_status',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Статус заявки в РР'),
        ),
        migrations.AddField(
            model_name='application',
            name='sex',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Пол'),
        ),
    ]
